### PR TITLE
Added default parameters for Concept class

### PR DESCRIPTION
**Pull request by AmartC**

### CODE REVIEW

**Comment by cmoesel** [comment]
Curious -- why is this needed?  Usually we would represent "no data" as `undefined` or `null` rather than an empty string.  Now any code that checks `myConcept.display == null` will fail...

**Comment by cmoesel** [comment]
This also broke a bunch of unit tests (as evidenced by the Travis report linked to by the red X).  It really should not have been merged with broken tests...

**Comment by AmartC** [comment]
Mark and I had previously been discussing this as a change to pass some importer test cases. However, we decided against it and went about it a different route. We can delete this branch.

**Comment by cmoesel** [comment]
Oh!  I misread it and thought it was already _merged_.  Now I see it was _closed_ -- so no harm done!  Sorry for the confusion!

**Pull request closed without merging**
